### PR TITLE
Reportfix

### PR DESCRIPTION
**Pull request by dalekunce**

### CODE REVIEW

**Comment by dalekunce** [comment]
@danbjoseph can you test and deploy this branch first thing tomorrow. @emilyeros this fixes the issue with the report. single district pages still not done.

**Comment by danbjoseph** [comment]
you've included an automated update of node packages?

**Comment by dalekunce** [comment]
its useful, I try and use it alot.

**Comment by danbjoseph** [comment]
oh, it's just a stand-alone script? it's not linked to the build process?

**Comment by dalekunce** [comment]
yeah, its stand alone but can be called anytime. Its not linked to the build process, that would potentially break things.

**Comment by danbjoseph** [comment]
yes. i know. that's why i was confused at first.

**Comment by danbjoseph** [comment]
the webshot bit is giving me trouble when testing locally
```
[17:27:46] Starting 'webshot'...
internal/child_process.js:294
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:294:26)
    at Object.exports.spawn (child_process.js:378:9)
    at Function.spawn (/Users/sig/Documents/github/americanredcross/measles-dashboard/node_modules/cross-spawn/index.js:87:19)
    at spawnPhantom (/Users/sig/Documents/github/americanredcross/measles-dashboard/node_modules/webshot/lib/webshot.js:201:32)
    at spawn (/Users/sig/Documents/github/americanredcross/measles-dashboard/node_modules/webshot/lib/webshot.js:105:14)
    at /Users/sig/Documents/github/americanredcross/measles-dashboard/node_modules/webshot/lib/webshot.js:117:16
    at FSReqWrap.cb [as oncomplete] (fs.js:258:19)
```

**Comment by danbjoseph** [comment]
phantomjs is installed

**Comment by dalekunce** [comment]
check your node version? I'm running 7.10.0

**Comment by danbjoseph** [comment]
LTS is 6.10.3 and 
```
nvm install 7.10.0
> Version '7.10.0' not found - try `nvm ls-remote` to browse available versions.
```

**Comment by dalekunce** [comment]
```nvm install v7``` needs to be >v7 because autoprefixer needed a version bump.

**Pull request merged**
